# Generated by Django 2.1.3 on 2018-12-02 22:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
